### ISSUE TITLE
Inaccessible due to its protection level

### ISSUE THREAD

**Issue by Sandstedt** [sienaiwun/unity_lightcookie_caustic#1]
In Unity 2019.3.6 using URP, i get a lot of errors like this:

`Packages\src\com.unity.render-pipelines.lightweight@5.7.2\Editor\ShaderGraph\LightWeightUnlitSubShader.cs(14,39): error CS0122: 'IUnlitSubShader' is inaccessible due to its protection level`

`Packages\src\com.unity.render-pipelines.lightweight@5.7.2\Editor\ShaderGraph\LightWeightUnlitSubShader.cs(12,6): error CS0122: 'FormerNameAttribute' is inaccessible due to its protection level`

**Comment by Sandstedt** [comment]
(work fine in 2019.1.13)
